### ISSUE TITLE
l need tutorials

### ISSUE THREAD

**Issue by txj-mssl** [Schweini07/Dialogbox#1]

**Comment by Schweini07** [comment]
I can make a tutorial video when you think it is neccessary.
The README also provides helpful information, if you want to look into that.

**Comment by txj-mssl** [comment]
Thanks, I need a video tutorial

**Comment by Schweini07** [comment]
Right now I'm setting up a Wiki page, this should help more than a video, but until then just ask what you don't understand

**Comment by txj-mssl** [comment]
I need video because I'm a novice

**Comment by txj-mssl** [comment]
Can this plug-in help me build a visual novel?

**Comment by Schweini07** [comment]
Yes definitely, it's design philosophy is made exactly for games like that. Tutorial coming soon, until then: read the first two wiki pages

**Comment by Schweini07** [comment]
https://youtu.be/LVjcTBjyehU

Here is the tutorial
