### ISSUE TITLE
Dialogbox is skipping lines.

### ISSUE THREAD

**Issue by KKarol01** [Schweini07/Dialogbox#3]
### Issue Description
Dialogbox is skipping randomly lines. Sometimes it is the second line,
sometimes it isn't. It always skips more than one line, but doesn't follow any pattern whatsoever.
I am confident thanks to the power of ultimate debugging tool which is print method
that i run Dialogbox::show_text() only once.

### Steps that i took:

- I dragged and dropped a scene file "Dialogbox.tscn"
 to: _/root/MainScene/CanvasLayer/Dialogbox_
- I am calling method show_text() with a single argument which is an array of strings.

### Configuration
- I turned off Play Sound
- I set **use_input_trigger** and **use_speedup** to **ui_interact**(created by me) and **ui_select** respectively.
- I changed text margin
- I turned off sound and font

**Comment by Schweini07** [comment]
Did you add the .tscn? You can just add it when you are clicking on the add node button, even tough it probaly won't work. A test project would be nice

**Comment by KKarol01** [comment]
Here is a link to my project.
[https://drive.google.com/open?id=1a5GWbTU6ONPsoQDSAZDBcQy095dx_J-H](https://drive.google.com/open?id=1a5GWbTU6ONPsoQDSAZDBcQy095dx_J-H)

**Comment by Schweini07** [comment]
Ok, I looked in the project but had no problems. I think this is related to #2, if you wouldn't mind could try the project of the issue author and look if it also doesn't work there?

**Comment by KKarol01** [comment]
Yes, the problem still appears, although, in youwenti's dialog there are only two lines so 1 on 2 restarts displays the dialog fully, next run doesn't display second line.

**Comment by Schweini07** [comment]
I would probably think that this is a hardware update. I tried it on 2 Laptops, one with Linux and one with Windows. My PC also has Linux. But it always worked. I'll try to fix it soon.

**Comment by KKarol01** [comment]
Don't bother, it's not worth it. I will write new script. Thank you for your help anyway. Have a great day!
